### ISSUE TITLE
Hedera SDK Update to v2.15

### ISSUE THREAD

**Issue by svetlio8** [LimeChain/hashport-validator#383]
Update Hedera SDK to v2.12 - expected on Feb 14 2022. Expected to fix the issues with hitting unhealthy Hedera Nodes found in #376 

We will need 1 week on testnet.
First 1-2 days only LimeChain node + monitoring. If ok > other validators

**Comment by failfmi** [comment]
https://github.com/hashgraph/hedera-sdk-go/milestone/21. The new algorithm implementation is delayed to the next release (Feb 28) as the final design is requiring additional discussion.

**Comment by svetlio8** [comment]
Postponed till 21 March

**Comment by failfmi** [comment]
Expected version: `v2.12.0-beta.1`. Non-beta version `v2.12.0` will be released April 4.

**Comment by failfmi** [comment]
Update to latest released version, currently `v2.15`
