### ISSUE TITLE
Dashboard Metrics for NFT

### ISSUE THREAD

**Issue by svetlio8** [LimeChain/hashport-validator#391]
We will need to implement the same metrics for the NFT assets as we already have for the fungible.

❗ We will need both the NFT implementation and the metrics. At the moment they are on NFT [branch](https://github.com/LimeChain/hashport-validator/tree/develop) & Metrics [branch](https://github.com/LimeChain/hashport-validator/tree/feature/metrics)

- Locked same as #353
- Minted - #354
- Balance between networks - #357

- ❓ it is possible that new metrics will be needed based on the requests?

**Comment by bibitibooo1** [comment]
This task will become a lot larger with the amount of new tokens coming. To think of organising the panels in Grafana. 
-> NFTs
-> FT

**Comment by bibitibooo1** [comment]
- Add prefix to filter on a new panel. 
- Add NTF to the names?
