### ISSUE TITLE
Cache chainId instead of fetching it every time

### ISSUE THREAD

**Issue by failfmi** [LimeChain/hashport-validator#405]
Currently,
```go
var chain *big.Int
chain, e := ew.evmClient.ChainID(context.Background())
if e != nil {
  ew.logger.Errorf("[%s] - Failed to retrieve chain ID.", eventLog.Raw.TxHash)
  return
}
```
is called on every EVM related transfer, when this is data that can be cached upon validator start. It is not expected to change. Suggestion would be to cache it in`evmClient`.

**Comment by svetlio8** [comment]
Fixed in https://github.com/LimeChain/hashport-validator/pull/412
