### ISSUE TITLE
Research Proof of Reserves

### ISSUE THREAD

**Issue by Petyo-Lukanov** [LimeChain/hashport-validator#408]
Research the proof of reserves and how it can be applied in the case of HashPort

**Comment by svetlio8** [comment]
Summary:

Proof of Reserves (Is the Hashport platform solvent?)
Example for wrapped HBARs:
- Chainlink gets the Hashport’s Bridge account amount of locked HBARs (or reserve) by querying the Hedera network. This information can be updated on every X time period.
- Once the data is received TX is triggered to update the Proof of Reserve Contract (GAS COST - needed LINK token in the smart contract).
- Based on the Proof of Reserve Contract, dApps on Ethereum/Polygon can validate (compare minted on the Ethereum/Polygon vs reserve/locked in Bridge Account) if the reserve is enough and proceeds with the DeFi user’s TX.

Chainlink blog:
- [example](https://blog.chain.link/chainlink-proof-of-reserve-bringing-transparency-to-defi-collateral/)
- [example](https://blog.chain.link/verify-stablecoin-collateral-with-chainlink-proof-of-reserve/) 

Get request [docks](https://docs.chain.link/docs/make-a-http-get-request/)

Important notes:
- ️Note on Funding Contracts: Making a GET request will fail unless your deployed contract has enough LINK to pay for it. Learn how to Acquire testnet LINK and Fund your contract.
- The return value must fit within 32 bytes. If the value is bigger than that, make multiple requests.

TODO: 
Is it worth it? (Gas cost ETAs)
