### ISSUE TITLE
Interface and mock for gorm.DB

### ISSUE THREAD

**Issue by ghost** [LimeChain/hashport-validator#438]
Currently, we can't mock gorm.DB as it is concrete struct. In order to do It we need to do the following:
- Create an interface for gorm.DB
- Create Mock which implements the new interface

**Comment by Psykepro** [comment]
found a more widely used approach for mocking `gorm.DB` which is by using `sqlmock` package. Here is info about it:

https://github.com/DATA-DOG/go-sqlmock
https://github.com/go-gorm/gorm/issues/1525
https://betterprogramming.pub/how-to-unit-test-a-gorm-application-with-sqlmock-97ee73e36526
