### ISSUE TITLE
Interface proposal

### ISSUE THREAD

**Issue by svetlio8** [LimeChain/hashport-validator#484]
Based on the [user stories](https://www.notion.so/limechain/Hashgraph-SDK-User-Stories-052465694a034fa0be1d8a37ae4d39d9) in Hashport SDK #476
 please create an interface for the needed functionalities, once we have it we can split the different functionalities as separate tasks.

**Comment by Psykepro** [comment]
https://www.notion.so/limechain/Hashport-SDK-interface-proposal-64d054d1ea1046cd908d67c77283ef6d
