### ISSUE TITLE
Research for Update tokens service

### ISSUE THREAD

**Issue by svetlio8** [LimeChain/hashport-validator#600]
Research for Update tokens service based on #593:
- check for logic duplication (validator/service)
- pass new configuration as a message
- check for signatures (majority) as init 2/2 multi-sign:
* validate the config on a sign.
- check for message overflow - update the config on multiple messages. topic message submission max size = 1024 bytes [link](https://docs.hedera.com/guides/docs/hedera-api/consensus-service/consensussubmitmessage#consensusmessagechunkinfo)
- Example the `bridge.yml` config on [testnet](https://testnet.mirrornode.hedera.com/api/v1/topics/0.0.34726830/messages) is split into 5 chunks. We will need to assemble the 5 chunks and parse the config.

**Comment by failfmi** [comment]
* Create a new topic message watcher that listens the topic that contains the bridge configuration
    * Make the algorithm for listening the topic in such a way, that when new messages are added, they are parsed correctly consequently. Use the topic message chunk info `number` and `total`
        * https://docs.hedera.com/guides/docs/mirror-node-api/rest-api#topics
        * Example: https://testnet.mirrornode.hedera.com/api/v1/topics/0.0.34726830/messages
