### ISSUE TITLE
API: Fee Amounts for NFTs

### ISSUE THREAD

**Issue by failfmi** [LimeChain/hashport-validator#621]
* Return the fee amounts for NFTs, both for Hedera and the corresponding wrapped networks.
    * For wrapped NFTs, the payment token + amount will need to be fetched from the Router Smart Contract 

* Might be added either in `min-amounts` or in another endpoint/

**Comment by svetlio8** [comment]
Issue moved to [LimeChain/hashport-api #74](https://github.com/LimeChain/hashport-api/issues/74) via [**ZenHub**](https://www.zenhub.com/)
