### ISSUE TITLE
Deploy FT on Testnet

### ISSUE THREAD

**Issue by failfmi** [LimeChain/hashport-validator#626]
Based on the requested EVM fungible tokens for integration on Ethereum/Polygon mainnet, [deploy](https://github.com/LimeChain/hashport-contracts#token-deployment) similar fungible tokens on EVM testnet, which have the following properties:

* the same name
* the same symbol
* the same decimals

After the mocked versions of the EVM fungible tokens are deployed, create wrapped versions to the expected wrapped networks, but for testnet:
* Hedera -> Hedera Testnet
* Polygon -> Polygon Mumbai Testnet
* Ethereum -> Ethereum Ropsten Testnet

* EVM 
     * name based on requirements
     * symbol based on requirements
     * decimals should be the same as the native one unless there is an explicit requirement
     * [transfer ownership](https://github.com/LimeChain/hashport-contracts#transfer-ownership-of-a-contract) to Diamond Router Contract, so that he can mint when necessary
* Hedera
    * name based on requirements
    * symbol based on requirements
    * decimals - if the native version has > 8 decimals, create the wrapped with 8 decimals
    * add supply key, so that the bridge account can execute mint
    * add yourself as admin key, so that you can change something in case it has not been properly set
    * the treasury account must be the bridge account

After the wrapped versions are created, [add](https://github.com/LimeChain/hashport-contracts#update-native-token-to-router) the mocked versions to the Diamond Router Contract. Use the fee percentages based on the initial requirements.

Last but not least, update the bridge configuration based on the other requirements, either in the bridge.yml, or in the topic, that stores it.

**Comment by bibitibooo1** [comment]
https://docs.google.com/spreadsheets/d/1R2KLRS-JxS8v5RsBwkfhEmxGtr1cQcy0mqFxBV2G4sM/edit#gid=0
https://docs.google.com/spreadsheets/d/13CHmzGzLcandRPcrK_mnjc6UDstwqGi3Hfo1N9xIejo/edit#gid=0
