### ISSUE TITLE
Errors caused by Hedera ID change

### ISSUE THREAD

**Issue by svetlio8** [LimeChain/hashport-validator#633]
After the implementation of the Replace Hedera network ID based on HIP-26 #591, we will face a situation where we will have old messages with Hedera ID = 0 and new messages with Hedera ID = 296. 

To reproduce the error you will need to:
- have a read-only validator 
- have the new Hedera ID = 296 in the config 
- Process an old message with Hedera ID = 0  (for example run the validator from the beginning)

Expected problems: Messages will not be processed, because they will be with 0 instead of 296 from EVM to 0. Events with unlocking, mint will throw an error.

Keep in mind that the network ID is stored also in the DB `transfers` table: `source_chain_id`, `target_chain_id`, `native_chain_id`

Whenever we display (Example /transfer-history) 0 for Hedera network ID, replace it with 296 (the new id from the config)

**Comment by Psykepro** [comment]
committed current progress in branch: https://github.com/LimeChain/hashport-validator/tree/feature/hedera-id-backwards-compatibility
