### ISSUE TITLE
Error: "FATA Provided address [] is not an EVM smart contract"

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#662]
Based on the bugs from #653:

When removing Ropsten from the Bridge config, if the client is left in node.yml, there's an error: FATA Provided address [] is not an EVM smart contract

Note after some research: https://github.com/LimeChain/hashport-validator/blob/main/bootstrap/services.go#L90 - to test if there's RouterContractAddress.

**Comment by Psykepro** [comment]
I will skip creating tests for bootstrap files because this will increase afterward the work on the project because will need to do changes in those tests for each change in each client, service, and repository.
