### ISSUE TITLE
Green light for BNB Chain and Avalanche: Deploy tokens

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#671]
Binance Smart Chain's new name -> BNB Chain

**Deploy tokens to cover the different flows:**
Hedera native FT (JAM/CLXY/REV3L on both networks, HST on Avalanche only)
wrap BSC & Avalanche native tokens (BNB & AVAX) on Hedera
wrap test NFT on both BSC & Avalanche

**Comment by bibitibooo1** [comment]
At least one Hedera Native token + NFT + BNB + Avalanche token + check the issue with the HBAR

**Comment by Psykepro** [comment]
Scripts Executed and Results for AVALANCHE Testnet:

AVAX Testnet

#####################################
#  Create Native Tokens For Hedera: #
#####################################

----------
Fungible:
----------

npx hardhat deploy-token --network avax --name USDC  --symbol USDC  --decimals 6

############ 
# Results: #
############

  0x7480c246F0831DA2a8C677a78B53904Dd5662F8d - USDC 


###################################
#  Update Native Token to Router: #
###################################

npx hardhat update-native-token     --network avax     --router 0x2e2de3444E0b83bdb4FBB2688D2fB399cCaa4C85     --native-token 0x7480c246F0831DA2a8C677a78B53904Dd5662F8d     --fee-percentage 500     --status true

############ 
# Results: #
############

All successful

######################################
#  Create Wrapped Tokens For Hedera: #
######################################

npx hardhat update-native-token \
    --network avax \
    --router 0x2e2de3444E0b83bdb4FBB2688D2fB399cCaa4C85 \
    --native-token 0x7480c246F0831DA2a8C677a78B53904Dd5662F8d \
    --fee-percentage 500 \
    --status true

----------
Fungible:
----------

npx hardhat deploy-wrapped-token --network avax --name HST[43113x] --symbol HST[43113x] --decimals 8

---------------
Non-Fungible:
---------------

npx hardhat deploy-wrapped-erc721-transfer-ownership --network avax --name 0.0.15678175[43113x] --symbol 0.0.15678175[43113x] --router 0x2e2de3444E0b83bdb4FBB2688D2fB399cCaa4C85

############ 
# Results: #
############

----------
Fungible:
----------

0x46ca1375b3E9FC10eaD6D8B5B739c2596CC67cFf - HST

---------------
Non-Fungible:
---------------

0x4559579731Ed71a705Bb43cED11C2BF6d661a819 - TESTNFT

##############################################################
#  Transfer Ownership for Fungible Tokens to Diamond Router: #
##############################################################

npx hardhat transfer-ownership --network avax --contract 0x4559579731Ed71a705Bb43cED11C2BF6d661a819 --new-owner 0x2e2de3444E0b83bdb4FBB2688D2fB399cCaa4C85

npx hardhat transfer-ownership --network avax --contract 0x708bBD707147BF4C065f8707bdB0Facd7a82d661 --new-owner 0x2e2de3444E0b83bdb4FBB2688D2fB399cCaa4C85

############ 
# Results: #
############

All successfull


#########################################
#  Upgrade diamond to support ERC-721: #
#########################################

npx hardhat upgrade-erc721-support --network avax --router 0x2e2de3444E0b83bdb4FBB2688D2fB399cCaa4C85

############ 
# Results: #
############

All successfull

#############################################
#  Add USDC as Payment Token to the Router: # 
#############################################

npx hardhat set-payment-token --network avax --router 0x2e2de3444E0b83bdb4FBB2688D2fB399cCaa4C85 --payment-token 0x7480c246F0831DA2a8C677a78B53904Dd5662F8d --status true


########################################
#  Set ERC-721 Payment Tokens and Fee: # 
########################################

--------------
Hedera NFTs:
--------------

npx hardhat set-erc721-payment --network avax --router 0x5f953791A42bD221134E50b01fcfFD4A4f9713A0 \
    --payment-token 0x7480c246F0831DA2a8C677a78B53904Dd5662F8d \
    --fee 1000000 \
    --erc721 0x4559579731Ed71a705Bb43cED11C2BF6d661a819

############ 
# Results: #
############

All successful
