### ISSUE TITLE
EVM-side fees per user when unlocking

### ISSUE THREAD

**Issue by vectorman1** [LimeChain/hashport-validator#684]
This issue is relevant to the process where an EVM-native asset has been previously ported somewhere, burned, and the user is requesting to unlock his tokens to reclaim possession.

Extend `unlock(...)` [link](https://github.com/LimeChain/hashport-contracts/blob/main/contracts/facets/RouterFacet.sol#L112) in RouterFacet by adding a parameter for the fee policy being used for the transaction. 

Validators will have to additionally sign the passed address, in order for verification to pass. 

Additionally - `distributeRewards` should be extended by adding a parameter for the Fee Policy. If the param has been passed, call the policy contract for the fee amount. 

[User Stories](https://www.notion.so/limechain/Fee-Per-User-User-Stories-f7fc1ebd1cdc45a98c8f50b74ecc968f)

**Comment by Daniel-K-Ivanov** [comment]
To be technically correct, we have to add additional argument for the `fee` that must be charged. The fee is calculated by the validator nodes. The correctness of the value for the `fee` is verified on the smart contract side by doing 2 things:
- smart contract verifies that the `fee` provided is no more than the standard 0.5% fee
- smart contract verifies that the provided signatures include the `fee` as part of their payload - basically validators attesting what the fee should be

**Comment by bibitibooo1** [comment]
[Notion file](https://limechain.notion.site/limechain/MetaLock-Notes-Potentially-change-the-name-056ff5f92ce6459ba6721ab0c3c29ed4)

**Comment by trayanm** [comment]
The unlock method emits event 
```
event Unlock(
        uint256 sourceChain,
        bytes transactionId,
        address token,
        uint256 amount,
        address receiver,
        uint256 serviceFee
    );
```
The meaning of the last field `uint256 serviceFee` will be changed as:
- if calculated fee is passed to `unlock(...)` and if the calculated fee respects the rules (less than 0.5% and signed) - serviceFee is the calculated fee
- if calculated fee is not passed - no changes, i.e. serviceFee is the result of LibFeeCalculator.distributeRewards
