### ISSUE TITLE
Research Asset Transfer "unstucking"

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#690]
-> Research how much time the following task would take: 

Whenever a user transaction fails for a specific reason such as TOKEN_NOT_ASSOCIATED, add the transaction data in the DB. Introduce a new API endpoint that uses Basic Authentication and accepts a TX ID as argument. Once called, the validator executes the “unstucking” of the Hedera transaction by getting the transaction data from the DB. Once executed, the transaction is marked as successful in the DB so that a sequent call to the API endpoint will not result in processing the transaction again.

**Comment by Psykepro** [comment]
Closing this ticket since the fix was implemented in the front-end.
