### ISSUE TITLE
Research failed to submit scheduled transfer transaction

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#704]
LimeChain, Animoca + 2 BCW validators have the following error:

ERRO[2022-08-14T04:56:02.358397574Z] [0x3c566ab021e57d15ea2dd5dc902ba02c590c57371ce14786b67d759fec1cbf02-518] - Failed to submit scheduled transfer transaction. Error [retry 10/10: error].  context="Scheduled Service"

**Comment by bibitibooo1** [comment]
Is it currently reproduced on mainnet?

**Comment by svetlio8** [comment]
So far we didn't get the same error. It seems that the error happens only once
