### ISSUE TITLE
Check for open-source KMS solutions

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#717]
+ get back to Tai with the options

**Comment by Psykepro** [comment]
https://www.vaultproject.io/ - Can be set up on GCP VM. It has a Key Rotation mechanism. It supports Hedera keys (ed25519) https://github.com/hashicorp/vault/issues/11035.
https://www.nucypher.com/ - Is a decentralized KMS. It doesn't have a Key Rotation mechanism and Key Generation.

**Comment by bibitibooo1** [comment]
+ Create trial account to validate if ed25519 and ecdsa are supported.

**Comment by Psykepro** [comment]
It looks like it supports both key types `ed25519` and `ecdsa`. https://www.vaultproject.io/api-docs/secret/transit#parameters
Хere is the Pricing: https://cloud.hashicorp.com/products/vault/pricing
For ethereum keys I think it needs the ethereum plugin: https://github.com/immutability-io/vault-ethereum
