### ISSUE TITLE
Add logs and further research the INVALID_NODE_ACCOUNT error

### ISSUE THREAD

**Issue by rokn** [LimeChain/hashport-validator#724]
We should log which node is wrong so we can pinpoint if a single node is causing problems.

**Comment by Daniel-K-Ivanov** [comment]
Most probably the issue lies within the retry submission mechanism of the SDK. When retries 10/10 are hit, the target node is changed. There is a chance that the SDK simply submits the Transaction to a new node without re signing it.

**Comment by bibitibooo1** [comment]
https://www.notion.so/limechain/INVALID_NODE_ACCOUNT-748219bfb68f416c94943984b31ed593
