### ISSUE TITLE
Research 3rd party RPC provider for BSC/Avax

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#730]
To have all networks in order to avoid double payment.
+ migrate RPC urls of the Validator and RO Validator

**Comment by Psykepro** [comment]
1. Moralis: 
1.1 Pricing: 
[ENTERPRISE.png](https://images.zenhubusercontent.com/62334a19023ea97e4c2eb50a/3d7a72e6-6fc0-4a54-801e-940beaa153e7)
1.1. Networks:
1. Ethereum (ETH)
2. BNB Smart Chain (Binance Smart Chain)
3. Polygon (MATIC)
4. Fantom (FTM)
5. CRONOS (CRO)
6. Avalanche (AVAX)
7. Solana (SOL)
 

2. QuickNode
 2. 1. Pricing:
![10 Mition.png](https://images.zenhubusercontent.com/62334a19023ea97e4c2eb50a/7f7900f7-9f48-46fd-922d-d792624ee635)
 2. 2. Networks:
* Ethereum
* Solana
* Polygon
* Binance Smart Chain
* Algorand
* Arbitrum
* Arbitrum Nova
* BETA
* Avalanche
* Bitcoin
* Celo
* Fantom
* Gnosis
* Harmony
* Optimism

Looks like QuickNode is the best option as it has better pricing and more networks supported.
