### ISSUE TITLE
E2E fixing

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#773]
We should finish the refactoring started on pr #618. It mainly consists of extracting and splitting the code in the e2e_test.go file to different components.
We should also fix a couple of problems:

- There are some places where logs are broken probably from copy paste, for example:
```
fmt.Printf("Could not find any scheduled transactions for account [%s]. Trying again. Time left: ~[%d] seconds\n", setupEnv.Clients.Hedera.GetOperatorAccountID(), timeLeft)
```
This should show the correct account as it's currently showing the same one every time.

- There shouldn't be any arbitrary `time.Sleep` calls. If something needs to be waited for it should use some kind of other mechanism like polling or whatever fits the need, but not just waiting for X seconds and trying once. The only place where time.Sleep should be used is for timeouts and backoff between polling retries.

**Comment by rokn** [comment]
We should also add a short check for the E2E like this:
```golang
if testing.Short() {
        t.Skip("skipping test in short mode.")
}
```
That would enable us to skip them easily when running:
`go test -short`
