### ISSUE TITLE
Research and estimate test coverage change

### ISSUE THREAD

**Issue by bibitibooo1** [LimeChain/hashport-validator#781]
Total to include both tested and not tested files so that the metric is more accurate.

**Comment by trayanm** [comment]
Report from branch [dev_773_e2e_refactor_fixing](https://github.com/LimeChain/hashport-validator/tree/dev_773_e2e_refactor_fixing) ordered by Coverage % asc:
**4045** of **6465** lines covered

<table>
    <tr>
        <td>Files</td>
        <td>Tracked lines</td>
        <td>Covered</td>
        <td>Partial</td>
        <td>Missed</td>
        <td>Coverage %</td>
    </tr>
    <tr>
        <td>app/helper/http/retry-logger.go</td>
        <td>16</td>
        <td>0</td>
        <td>0</td>
        <td>16</td>
        <td>0.00%</td>
    </tr>
    <tr>
        <td>app/helper/http/error-response.go</td>
        <td>11</td>
        <td>0</td>
        <td>0</td>
        <td>11</td>
        <td>0.00%</td>
    </tr>
    <tr>
        <td>app/services/contracts/service.go</td>
        <td>71</td>
        <td>0</td>
        <td>0</td>
        <td>71</td>
        <td>0.00%</td>
    </tr>
    <tr>
        <td>app/clients/hedera/client.go</td>
        <td>215</td>
        <td>9</td>
        <td>1</td>
        <td>205</td>
        <td>4.19%</td>
    </tr>
    <tr>
        <td>app/services/lock-event/service.go</td>
        <td>179</td>
        <td>25</td>
        <td>2</td>
        <td>152</td>
        <td>13.97%</td>
    </tr>
    <tr>
        <td>app/process/handler/read-only/fee-transfer/handler.go</td>
        <td>152</td>
        <td>26</td>
        <td>1</td>
        <td>125</td>
        <td>17.11%</td>
    </tr>
    <tr>
        <td>app/persistence/db_conn.go</td>
        <td>27</td>
        <td>7</td>
        <td>0</td>
        <td>20</td>
        <td>25.93%</td>
    </tr>
    <tr>
        <td>app/router/transfer/transfer.go</td>
        <td>53</td>
        <td>17</td>
        <td>1</td>
        <td>35</td>
        <td>32.08%</td>
    </tr>
    <tr>
        <td>app/services/fee/distributor/distributor.go</td>
        <td>90</td>
        <td>29</td>
        <td>0</td>
        <td>61</td>
        <td>32.22%</td>
    </tr>
    <tr>
        <td>app/process/watcher/evm/watcher.go</td>
        <td>505</td>
        <td>178</td>
        <td>11</td>
        <td>316</td>
        <td>35.25%</td>
    </tr>
    <tr>
        <td>app/process/handler/read-only/mint-hts/handler.go</td>
        <td>74</td>
        <td>30</td>
        <td>3</td>
        <td>41</td>
        <td>40.54%</td>
    </tr>
    <tr>
        <td>config/config.go</td>
        <td>33</td>
        <td>14</td>
        <td>3</td>
        <td>16</td>
        <td>42.42%</td>
    </tr>
    <tr>
        <td>app/process/handler/read-only/fee/handler.go</td>
        <td>119</td>
        <td>51</td>
        <td>6</td>
        <td>62</td>
        <td>42.86%</td>
    </tr>
    <tr>
        <td>app/model/auth-message/auth-message.go</td>
        <td>147</td>
        <td>66</td>
        <td>8</td>
        <td>73</td>
        <td>44.90%</td>
    </tr>
    <tr>
        <td>app/process/watcher/transfer/watcher.go</td>
        <td>282</td>
        <td>129</td>
        <td>17</td>
        <td>136</td>
        <td>45.74%</td>
    </tr>
    <tr>
        <td>app/persistence/db.go</td>
        <td>23</td>
        <td>11</td>
        <td>0</td>
        <td>12</td>
        <td>47.83%</td>
    </tr>
    <tr>
        <td>app/clients/evm/client.go</td>
        <td>173</td>
        <td>83</td>
        <td>0</td>
        <td>90</td>
        <td>47.98%</td>
    </tr>
    <tr>
        <td>app/clients/hedera/mirror-node/client.go</td>
        <td>400</td>
        <td>199</td>
        <td>6</td>
        <td>195</td>
        <td>49.75%</td>
    </tr>
    <tr>
        <td>app/core/server/server.go</td>
        <td>20</td>
        <td>10</td>
        <td>0</td>
        <td>10</td>
        <td>50.00%</td>
    </tr>
    <tr>
        <td>app/helper/big-numbers/helper.go</td>
        <td>12</td>
        <td>7</td>
        <td>0</td>
        <td>5</td>
        <td>58.33%</td>
    </tr>
    <tr>
        <td>app/process/handler/read-only/burn/handler.go</td>
        <td>44</td>
        <td>26</td>
        <td>2</td>
        <td>16</td>
        <td>59.09%</td>
    </tr>
    <tr>
        <td>app/process/handler/message/handler.go</td>
        <td>136</td>
        <td>84</td>
        <td>3</td>
        <td>49</td>
        <td>61.76%</td>
    </tr>
    <tr>
        <td>app/model/fee-policy/flat_fee_per_token_policy.go</td>
        <td>37</td>
        <td>24</td>
        <td>4</td>
        <td>9</td>
        <td>64.86%</td>
    </tr>
    <tr>
        <td>app/process/watcher/message/watcher.go</td>
        <td>79</td>
        <td>52</td>
        <td>6</td>
        <td>21</td>
        <td>65.82%</td>
    </tr>
    <tr>
        <td>config/loggcp.go</td>
        <td>56</td>
        <td>38</td>
        <td>4</td>
        <td>14</td>
        <td>67.86%</td>
    </tr>
    <tr>
        <td>app/services/signer/evm/signer.go</td>
        <td>19</td>
        <td>13</td>
        <td>2</td>
        <td>4</td>
        <td>68.42%</td>
    </tr>
    <tr>
        <td>app/services/burn-event/service.go</td>
        <td>270</td>
        <td>187</td>
        <td>12</td>
        <td>71</td>
        <td>69.26%</td>
    </tr>
    <tr>
        <td>app/services/fee/calculator/calculator.go</td>
        <td>36</td>
        <td>25</td>
        <td>3</td>
        <td>8</td>
        <td>69.44%</td>
    </tr>
    <tr>
        <td>app/helper/http/encode.go</td>
        <td>10</td>
        <td>7</td>
        <td>1</td>
        <td>2</td>
        <td>70.00%</td>
    </tr>
    <tr>
        <td>app/services/assets/assets.go</td>
        <td>421</td>
        <td>296</td>
        <td>28</td>
        <td>97</td>
        <td>70.31%</td>
    </tr>
    <tr>
        <td>app/model/message/message.go</td>
        <td>51</td>
        <td>36</td>
        <td>1</td>
        <td>14</td>
        <td>70.59%</td>
    </tr>
    <tr>
        <td>app/services/pricing/service.go</td>
        <td>353</td>
        <td>250</td>
        <td>17</td>
        <td>86</td>
        <td>70.82%</td>
    </tr>
    <tr>
        <td>config/node.go</td>
        <td>106</td>
        <td>76</td>
        <td>10</td>
        <td>20</td>
        <td>71.70%</td>
    </tr>
    <tr>
        <td>app/services/prometheus/service.go</td>
        <td>125</td>
        <td>93</td>
        <td>10</td>
        <td>22</td>
        <td>74.40%</td>
    </tr>
    <tr>
        <td>app/model/fee-policy/flat_fee_policy.go</td>
        <td>17</td>
        <td>13</td>
        <td>1</td>
        <td>3</td>
        <td>76.47%</td>
    </tr>
    <tr>
        <td>app/model/fee-policy/percentage_fee_policy.go</td>
        <td>18</td>
        <td>14</td>
        <td>1</td>
        <td>3</td>
        <td>77.78%</td>
    </tr>
    <tr>
        <td>app/model/fee-policy/helpers.go</td>
        <td>19</td>
        <td>15</td>
        <td>1</td>
        <td>3</td>
        <td>78.95%</td>
    </tr>
    <tr>
        <td>app/process/handler/read-only/nft/fee/handler.go</td>
        <td>110</td>
        <td>87</td>
        <td>2</td>
        <td>21</td>
        <td>79.09%</td>
    </tr>
    <tr>
        <td>app/helper/evm/helper.go</td>
        <td>45</td>
        <td>36</td>
        <td>1</td>
        <td>8</td>
        <td>80.00%</td>
    </tr>
    <tr>
        <td>app/router/utils/utils.go</td>
        <td>20</td>
        <td>16</td>
        <td>1</td>
        <td>3</td>
        <td>80.00%</td>
    </tr>
    <tr>
        <td>app/helper/mirror-node/api.go</td>
        <td>34</td>
        <td>28</td>
        <td>2</td>
        <td>4</td>
        <td>82.35%</td>
    </tr>
    <tr>
        <td>app/process/handler/fee-message/handler.go</td>
        <td>25</td>
        <td>21</td>
        <td>1</td>
        <td>3</td>
        <td>84.00%</td>
    </tr>
    <tr>
        <td>app/services/fee-policy/service.go</td>
        <td>208</td>
        <td>175</td>
        <td>6</td>
        <td>27</td>
        <td>84.13%</td>
    </tr>
    <tr>
        <td>config/logger.go</td>
        <td>26</td>
        <td>22</td>
        <td>0</td>
        <td>4</td>
        <td>84.62%</td>
    </tr>
    <tr>
        <td>app/persistence/transfer/transfer.go</td>
        <td>172</td>
        <td>150</td>
        <td>8</td>
        <td>14</td>
        <td>87.21%</td>
    </tr>
    <tr>
        <td>app/helper/timestamp/helper.go</td>
        <td>24</td>
        <td>21</td>
        <td>1</td>
        <td>2</td>
        <td>87.50%</td>
    </tr>
    <tr>
        <td>app/process/watcher/bridge-config/watcher.go</td>
        <td>26</td>
        <td>23</td>
        <td>1</td>
        <td>2</td>
        <td>88.46%</td>
    </tr>
    <tr>
        <td>app/services/bridge-config/service.go</td>
        <td>158</td>
        <td>140</td>
        <td>5</td>
        <td>13</td>
        <td>88.61%</td>
    </tr>
    <tr>
        <td>config/bridge.go</td>
        <td>115</td>
        <td>102</td>
        <td>0</td>
        <td>13</td>
        <td>88.70%</td>
    </tr>
    <tr>
        <td>app/services/utils/service.go</td>
        <td>40</td>
        <td>36</td>
        <td>1</td>
        <td>3</td>
        <td>90.00%</td>
    </tr>
    <tr>
        <td>app/helper/hedera/transaction-id.go</td>
        <td>31</td>
        <td>28</td>
        <td>0</td>
        <td>3</td>
        <td>90.32%</td>
    </tr>
    <tr>
        <td>app/helper/hedera/scheduled_transaction.go</td>
        <td>62</td>
        <td>57</td>
        <td>1</td>
        <td>4</td>
        <td>91.94%</td>
    </tr>
    <tr>
        <td>app/process/recovery/recovery.go</td>
        <td>58</td>
        <td>55</td>
        <td>0</td>
        <td>3</td>
        <td>94.83%</td>
    </tr>
    <tr>
        <td>app/process/handler/message-submission/handler.go</td>
        <td>58</td>
        <td>55</td>
        <td>1</td>
        <td>2</td>
        <td>94.83%</td>
    </tr>
    <tr>
        <td>app/persistence/fee/fee.go</td>
        <td>43</td>
        <td>42</td>
        <td>0</td>
        <td>1</td>
        <td>97.67%</td>
    </tr>
    <tr>
        <td>app/router/router.go</td>
        <td>10</td>
        <td>10</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/helper/fee/fee.go</td>
        <td>27</td>
        <td>27</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/helper/http/get.go</td>
        <td>17</td>
        <td>17</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/core/queue/queue.go</td>
        <td>7</td>
        <td>7</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/helper/hedera/nft.go</td>
        <td>79</td>
        <td>79</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/helper/memo/helper.go</td>
        <td>10</td>
        <td>10</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/helper/hedera/token.go</td>
        <td>6</td>
        <td>6</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/router/assets/assets.go</td>
        <td>63</td>
        <td>63</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/helper/decimal/helper.go</td>
        <td>30</td>
        <td>30</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/helper/message/helper.go</td>
        <td>14</td>
        <td>14</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/payload/transfer.go</td>
        <td>28</td>
        <td>28</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/router/response/response.go</td>
        <td>5</td>
        <td>5</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/clients/coin-gecko/client.go</td>
        <td>30</td>
        <td>30</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/persistence/status/status.go</td>
        <td>34</td>
        <td>34</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/services/contracts/members.go</td>
        <td>8</td>
        <td>8</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/persistence/message/message.go</td>
        <td>36</td>
        <td>36</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/router/burn-event/burn-event.go</td>
        <td>15</td>
        <td>15</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/persistence/schedule/schedule.go</td>
        <td>55</td>
        <td>55</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/watcher/price/watcher.go</td>
        <td>20</td>
        <td>20</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/clients/coin-market-cap/client.go</td>
        <td>31</td>
        <td>31</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/router/healthcheck/healthcheck.go</td>
        <td>10</td>
        <td>10</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/router/min-amounts/min-amounts.go</td>
        <td>16</td>
        <td>16</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/handler/mint-hts/handler.go</td>
        <td>12</td>
        <td>12</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/router/config-bridge/config-bridge.go</td>
        <td>8</td>
        <td>8</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/handler/burn-message/handler.go</td>
        <td>25</td>
        <td>25</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/handler/fee-transfer/handler.go</td>
        <td>12</td>
        <td>12</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/handler/nft/transfer/handler.go</td>
        <td>50</td>
        <td>50</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/handler/nft/fee-message/handler.go</td>
        <td>25</td>
        <td>25</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/watcher/fee-policy-config/watcher.go</td>
        <td>22</td>
        <td>22</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/process/handler/read-only/transfer/handler.go</td>
        <td>20</td>
        <td>20</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/clients/hedera/mirror-node/model/error/error.go</td>
        <td>13</td>
        <td>13</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
    <tr>
        <td>app/clients/hedera/mirror-node/model/transaction/transaction.go</td>
        <td>73</td>
        <td>73</td>
        <td>0</td>
        <td>0</td>
        <td>100.00%</td>
    </tr>
</table>
