### ISSUE TITLE
Fix Validator API call logs for GCP

### ISSUE THREAD

**Issue by rokn** [LimeChain/hashport-validator#782]
When the validator API is called there are logs for each request which are formatted with some coloring which is breaking in GCP logs.
![image (2)](https://user-images.githubusercontent.com/4174764/204558159-7f18fa61-6b48-457c-822f-8a6b4a617aaf.png)
<img width="933" alt="image" src="https://user-images.githubusercontent.com/4174764/204558633-551ddc9b-82b0-4dcd-9335-34e388c43eff.png">

**Comment by Coiling-Dragon** [comment]
<img width="956" alt="Screenshot 2022-11-30 at 18 41 00" src="https://user-images.githubusercontent.com/66465846/204858439-cf75a74a-8ef2-499d-a196-384089940d8b.png">
