### ISSUE TITLE
Investigate BSC log errors

### ISSUE THREAD

**Issue by rokn** [LimeChain/hashport-validator#785]
ERRO[2022-11-30T14:08:25.357354064Z] Failed to filter logs. Error: [limit exceeded]  context="EVM Router Watcher [56-0x9021926Be887355B76e60F4148eBB6b3f1fFAfCc]"

This is probably related to the BSC RPC

**Comment by svetlio8** [comment]
Probably moving to QuickNode [ref]( https://github.com/LimeChain/hashport-validator/issues/730) will be the solution
